In [2]:
import numpy as np

In [4]:
# one dimensional , similar to list
a= np.array([1,23,12,3,4,43,5])

In [5]:
a.ndim

1

In [6]:
type(np.array([1,23,12,3,4,43,5]))

numpy.ndarray

In [7]:
# Two dimensional array
array = np.array([[1,20,4,7],[32,23,9,5]])

In [8]:
L = [[ 1, 23,  4,  4],[32, 23,  4,  5]]

In [9]:
# to slice 1st value of first list inside complete list.
L[0][0]

1

In [10]:
array[1][0]

32

In [11]:
array[0][1]

20

In [12]:
array[0][0]

1

In [13]:
array[1][1]

23

In [14]:
array[0][3]

7

In [15]:
array[1][3]

5

In [16]:
array[1][2]

9

In [17]:
array.ndim

2

In [26]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.ndim

2

In [20]:
arr[0][0]

1

In [21]:
arr[2][2]

9

In [22]:
arr[1][0]

4

In [23]:
# 4x4 array of random numbers
random = np.random.randint(1,10,(4,4))
random

array([[5, 3, 9, 5],
       [4, 5, 2, 1],
       [3, 4, 5, 7],
       [4, 3, 9, 3]])

In [24]:
random[3][3]

3

In [25]:
# 4x2 array 4 times, by following, it's similar to matix format, row x column
np.random.randint(1,10,(4,4,2))

array([[[1, 5],
        [1, 1],
        [5, 4],
        [2, 2]],

       [[9, 8],
        [8, 5],
        [2, 7],
        [9, 2]],

       [[3, 8],
        [2, 5],
        [2, 6],
        [1, 8]],

       [[8, 2],
        [2, 2],
        [8, 3],
        [1, 1]]])

In [26]:
l = [1,2,3,4,5,6,7,8]

In [27]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
#If a list of all types of datatypes, np.array will convert entire list into higher order datatype.
l1 = [1,2,4,'vish',3.5,True,22]

In [20]:
# In case of l1, string is the higher order datatype than integer.
array = np.array(l1)
array

array(['1', '2', '4', 'vish', '3.5', 'True', '22'], dtype='<U32')

In [30]:
a = np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a.ndim

1

In [3]:
np.random.randint(2,20,(3,4))

array([[17, 11, 19, 17],
       [16, 19, 13,  8],
       [12,  2,  4,  2]])

In [4]:
np.random.randint(2,50,(2,3,4))

array([[[16, 18,  2, 30],
        [33, 11, 27, 11],
        [11, 33, 46,  3]],

       [[41, 49, 46, 45],
        [18, 48, 12, 35],
        [13, 28, 34, 30]]])

In [6]:
np.random.rand(3,3)

array([[0.40616634, 0.83013451, 0.3431581 ],
       [0.90166149, 0.48851633, 0.32201724],
       [0.98265711, 0.58116684, 0.19031542]])

In [8]:
a = np.random.randn(4,3)
a

array([[ 1.93879197,  0.06315404,  0.38795192],
       [ 0.70587779, -0.96769894,  2.11007231],
       [ 0.19530797, -0.30590702, -1.87655672],
       [ 0.52988722,  0.2276026 ,  1.56847874]])

In [9]:
a.reshape(3,4)

array([[ 1.93879197,  0.06315404,  0.38795192,  0.70587779],
       [-0.96769894,  2.11007231,  0.19530797, -0.30590702],
       [-1.87655672,  0.52988722,  0.2276026 ,  1.56847874]])

In [10]:
a.reshape(2,6)

array([[ 1.93879197,  0.06315404,  0.38795192,  0.70587779, -0.96769894,
         2.11007231],
       [ 0.19530797, -0.30590702, -1.87655672,  0.52988722,  0.2276026 ,
         1.56847874]])

In [11]:
a.reshape(6,2)

array([[ 1.93879197,  0.06315404],
       [ 0.38795192,  0.70587779],
       [-0.96769894,  2.11007231],
       [ 0.19530797, -0.30590702],
       [-1.87655672,  0.52988722],
       [ 0.2276026 ,  1.56847874]])

In [12]:
# a.reshape(1,12)
# a.reshape(12,1)

In [13]:
a.reshape(2,-1)

array([[ 1.93879197,  0.06315404,  0.38795192,  0.70587779, -0.96769894,
         2.11007231],
       [ 0.19530797, -0.30590702, -1.87655672,  0.52988722,  0.2276026 ,
         1.56847874]])

In [14]:
a.reshape(2,-12)

array([[ 1.93879197,  0.06315404,  0.38795192,  0.70587779, -0.96769894,
         2.11007231],
       [ 0.19530797, -0.30590702, -1.87655672,  0.52988722,  0.2276026 ,
         1.56847874]])

In [15]:
a.reshape(2,2,3)

array([[[ 1.93879197,  0.06315404,  0.38795192],
        [ 0.70587779, -0.96769894,  2.11007231]],

       [[ 0.19530797, -0.30590702, -1.87655672],
        [ 0.52988722,  0.2276026 ,  1.56847874]]])

In [16]:
# If dataset has n number of observations then, multiplication of reshape parameters should not exceed n.

In [21]:
array

array(['1', '2', '4', 'vish', '3.5', 'True', '22'], dtype='<U32')

In [22]:
array[2:5]

array(['4', 'vish', '3.5'], dtype='<U32')

In [23]:
array[1:6:2]

array(['2', 'vish', 'True'], dtype='<U32')

In [24]:
#Arrays behaves same as the lists 

In [25]:
array[::-1]

array(['22', 'True', '3.5', 'vish', '4', '2', '1'], dtype='<U32')

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr[0]

array([1, 2, 3])

In [29]:
arr[2]

array([7, 8, 9])

In [40]:
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [41]:
a5 = np.random.randint(2,90,(6,5))

In [42]:
a5

array([[36, 84, 61, 40, 12],
       [74, 24, 31, 58, 44],
       [73, 79,  8, 16,  8],
       [18, 72, 66, 75, 57],
       [33,  3, 86, 23, 63],
       [39, 68, 67, 11, 78]])

In [43]:
a5[a5>40]

array([84, 61, 74, 58, 44, 73, 79, 72, 66, 75, 57, 86, 63, 68, 67, 78])

In [44]:
a5[0,1]

84

In [45]:
a5[0,1] = 15

In [46]:
a5

array([[36, 15, 61, 40, 12],
       [74, 24, 31, 58, 44],
       [73, 79,  8, 16,  8],
       [18, 72, 66, 75, 57],
       [33,  3, 86, 23, 63],
       [39, 68, 67, 11, 78]])

In [50]:
a5[2,2] = 10


In [51]:
a5

array([[36, 15, 61, 40, 12],
       [74, 24, 31, 58, 44],
       [73, 79, 10, 16,  8],
       [18, 72, 66, 75, 57],
       [33,  3, 86, 23, 63],
       [39, 68, 67, 11, 78]])

In [52]:
a6 = np.random.randint(0,5,(3,3))

In [53]:
a7 = np.random.randint(0,5,(3,3))

In [54]:
a6

array([[4, 0, 2],
       [3, 4, 3],
       [3, 0, 3]])

In [57]:
a7

array([[0, 2, 1],
       [3, 0, 2],
       [4, 2, 3]])

In [58]:
a6*a7

array([[ 0,  0,  2],
       [ 9,  0,  6],
       [12,  0,  9]])

In [59]:
a6+10

array([[14, 10, 12],
       [13, 14, 13],
       [13, 10, 13]])

In [60]:
a6*2

array([[8, 0, 4],
       [6, 8, 6],
       [6, 0, 6]])

In [61]:
a6/0

C:\Users\svish\AppData\Local\Temp/ipykernel_31232/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\svish\AppData\Local\Temp/ipykernel_31232/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, nan, inf],
       [inf, inf, inf],
       [inf, nan, inf]])

In [62]:
a6**2

array([[16,  0,  4],
       [ 9, 16,  9],
       [ 9,  0,  9]], dtype=int32)

In [65]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [68]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
a+10

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [71]:
# row wise operations, under the condition that, number of row = array size
a+np.array([1,2,3])

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [73]:
a = np.ones((4,4))+10
a

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [79]:
b = np.array([[1,2,3,4]])

In [80]:
a+b

array([[12., 13., 14., 15.],
       [12., 13., 14., 15.],
       [12., 13., 14., 15.],
       [12., 13., 14., 15.]])

In [81]:
b.T

array([[1],
       [2],
       [3],
       [4]])

In [82]:
b

array([[1, 2, 3, 4]])

In [83]:
a6

array([[4, 0, 2],
       [3, 4, 3],
       [3, 0, 3]])

In [85]:
# Transpose of array
a6.T

array([[4, 3, 3],
       [0, 4, 0],
       [2, 3, 3]])

In [86]:
np.sqrt(a6)

array([[2.        , 0.        , 1.41421356],
       [1.73205081, 2.        , 1.73205081],
       [1.73205081, 0.        , 1.73205081]])

In [87]:
np.exp(a6)

array([[54.59815003,  1.        ,  7.3890561 ],
       [20.08553692, 54.59815003, 20.08553692],
       [20.08553692,  1.        , 20.08553692]])

In [89]:
np.log10(a6)

C:\Users\svish\AppData\Local\Temp/ipykernel_31232/3143830726.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a6)


array([[0.60205999,       -inf, 0.30103   ],
       [0.47712125, 0.60205999, 0.47712125],
       [0.47712125,       -inf, 0.47712125]])

In [93]:
list(range(1,20,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [94]:
# floating point should not be in the range function
list(range(1,20,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [95]:
np.arange(1,20,2.5)

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5])

In [96]:
np.arange(1.2,20.3,1.9)

array([ 1.2,  3.1,  5. ,  6.9,  8.8, 10.7, 12.6, 14.5, 16.4, 18.3, 20.2])

In [98]:
np.linspace(2,3,num = 20)

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [99]:
np.linspace(2,5,num = 40,retstep = True)

(array([2.        , 2.07692308, 2.15384615, 2.23076923, 2.30769231,
        2.38461538, 2.46153846, 2.53846154, 2.61538462, 2.69230769,
        2.76923077, 2.84615385, 2.92307692, 3.        , 3.07692308,
        3.15384615, 3.23076923, 3.30769231, 3.38461538, 3.46153846,
        3.53846154, 3.61538462, 3.69230769, 3.76923077, 3.84615385,
        3.92307692, 4.        , 4.07692308, 4.15384615, 4.23076923,
        4.30769231, 4.38461538, 4.46153846, 4.53846154, 4.61538462,
        4.69230769, 4.76923077, 4.84615385, 4.92307692, 5.        ]),
 0.07692307692307693)

In [100]:
np.logspace(2,4,num = 10,base = 10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

#### Identity Matrix

In [101]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
a6

array([[4, 0, 2],
       [3, 4, 3],
       [3, 0, 3]])

#### Matrix Multiplication

If the column of first matrix is same as row of the second matrix, then matrix multiplication is hold.
If A and B are two matrices, to hold matrix multiplication,Number of columns in A must be equal to number of rows in B
If A is n x m matrix then matrix B should be m x n
